spring:
  application:
    name: internet-banking-api-gateway

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: [health,actuator,info]